language: node_js
dist: trusty
sudo: required
node_js: 10
install:
  - npm install -g bower pulp purescript@0.12.0
script:
  - bower install && pulp test
after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_TOKEN | pulp login &&
  echo y | pulp publish --no-push
